version: "3"
services:
  cost-gateway-server:
    image: ghcr.io/canpok1/cost-gateway/server:latest
    env_file:
      - ".env"
    restart: always

networks:
  default:
    external:
      name: common-database-network
