dsn: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
lint:
  requireTableComment:
    enabled: true
  requireColumnComment:
    enabled: true
  requireColumns:
    enabled: true
    columns:
      - name: created_at
      - name: updated_at
exclude:
  - schema_migrations
docPath: docs/database
