// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: create.sql

package db

import (
	"context"
	"database/sql"
)

const insertCostType = `-- name: InsertCostType :execresult
INSERT INTO cost_types (type_name) VALUES (?)
`

func (q *Queries) InsertCostType(ctx context.Context, typeName string) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertCostType, typeName)
}
