// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

// コスト種別
type CostType struct {
	// コスト種別ID
	ID uint64
	// コスト種別名
	TypeName string
	// 作成日時(UTC)
	CreatedAt time.Time
	// 更新日時(UTC)
	UpdatedAt time.Time
}

// 月次コスト
type MonthlyCost struct {
	// コスト種別ID
	CostTypeID uint64
	// 年
	CostYear uint32
	// 月
	CostMonth uint32
	// 料金(円)
	CostYen uint32
	// 作成日時(UTC)
	CreatedAt time.Time
	// 更新日時(UTC)
	UpdatedAt time.Time
}
