// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: upsert.sql

package db

import (
	"context"
	"database/sql"
)

const upsertMonthlyCost = `-- name: UpsertMonthlyCost :execresult
INSERT INTO monthly_costs (
    cost_type_id, cost_year, cost_month, cost_yen
) VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    cost_yen = VALUES(cost_yen)
`

type UpsertMonthlyCostParams struct {
	CostTypeID uint64
	CostYear   uint32
	CostMonth  uint32
	CostYen    uint32
}

func (q *Queries) UpsertMonthlyCost(ctx context.Context, arg UpsertMonthlyCostParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertMonthlyCost,
		arg.CostTypeID,
		arg.CostYear,
		arg.CostMonth,
		arg.CostYen,
	)
}
